### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by VelocityFever** [belguawhale/DiscordSelfBot#1]
I think there's an issue with your code.
`Traceback (most recent call last):
  File "selfbot.py", line 277, in <module>
    client.run('email@gmail.com','pw')
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 490, in start
    yield from self.login(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 416, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 374, in _login_2
    self._update_cache(email, password)
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 198, in _update_cache
    f.write(self.http.token)
TypeError: write() argument must be str, not None
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x75ee1590>`
Umm... one thing. Is running the batch file required? I'm on Raspbian, so...

**Comment by belguawhale** [comment]
The batch file is for windows; what version of python are you using and what command are you using to run the bot?

**Comment by VelocityFever** [comment]
I am using python 3.5 and the command I use is `python3 selfbot.py`. I am using Raspbian minimal for a server.

**Comment by belguawhale** [comment]
Does the error happen right after you run it? Or did it run but then cause this error afterwards?

**Comment by VelocityFever** [comment]
Afterwards

**Comment by belguawhale** [comment]
This appears to be an issue with the discord.py library or your internet disconnecting temporarily rather than with my code. Did the selfbot work before this error happened?

**Comment by belguawhale** [comment]
Closing due to no response
